import {
  APPWRITE_API_KEY,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_PROJECT_ENDPOINT,
  APPWRITE_USER_COLLECTION_ID,
  APPWRITE_CODETIPS_COLLECTION_ID,
  APPWRITE_ARTICLES_COLLECTION_ID,
  APPWRITE_FEEDBACK_COLLECTION_ID,
  APPWRITE_OPPORTUNITIES_COLLECTION_ID,
  APPWRITE_SERVICEREQUESTS_COLLECTION_ID,
  TECH_IN_AFRICA,
  MEDIA_API_URL
} from "@env";


export const environments = {
  MEDIA_API_URL,
  TECH_IN_AFRICA,
  APPWRITE_API_KEY,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_PROJECT_ENDPOINT,
  APPWRITE_USER_COLLECTION_ID,
  APPWRITE_ARTICLES_COLLECTION_ID,
  APPWRITE_CODETIPS_COLLECTION_ID,
  APPWRITE_FEEDBACK_COLLECTION_ID,
  APPWRITE_OPPORTUNITIES_COLLECTION_ID,
  APPWRITE_SERVICEREQUESTS_COLLECTION_ID,
}